version: "3.9"

services:
  portfolio-service:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: bash /code/docker-entrypoint.sh
    container_name: portfolio-service
    image: portfolio-service
    volumes:
      - .:/code
      - ../portfolio-service-logs:/logs
      - static_volume:/code/static
      - media_volume:/code/portfolio/data/media
      - nginx_secrets:/etc/letsencrypt
    expose:
      - 8000
    env_file: ./.env

  nginx:
    image: jonasal/nginx-certbot:latest
    container_name: nginx-service
    restart: unless-stopped
    env_file:
      - ./nginx/nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/code/static
      - media_volume:/code/portfolio/data/media
      - nginx_secrets:/etc/letsencrypt
      - ./nginx/user_conf.d:/etc/nginx/user_conf.d

volumes:
  static_volume:
  media_volume:
  nginx_secrets:
