version: "3.9"

services:
  postgres:
    image: postgres:14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: ./.env

  portfolio-service:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: bash /code/docker-entrypoint.sh
    container_name: portfolio-service
    image: portfolio-service
    volumes:
      - .:/code
      - ../portfolio-service-logs:/logs
      - static_volume:/code/static
      - media_volume:/code/portfolio/data/media
    ports:
      - 8000:8000
    env_file: ./.env
    depends_on:
      - postgres

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - static_volume:/code/static
      - media_volume:/code/portfolio/data/media
    depends_on:
      - portfolio-service

volumes:
  static_volume:
  media_volume:
  postgres_data:
