version: "3.8"

services:
  postgres:
    container_name: postgres-service
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres -d postgres"
      interval: 3s
      timeout: 5s
      retries: 5
    image: postgres:13.1-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: portfolio-service
    env_file: .env.local
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: always

  portfolio-service:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: bash /code/docker-entrypoint.local.sh
    container_name: portfolio-service
    image: portfolio-service
    volumes:
      - .:/code
      - ../portfolio-service-logs:/logs
    ports:
      - 8000:8000
    depends_on:
      - postgres
    env_file: .env.local

networks:
  default:
    name: portfolio-service
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 100.100.107.0/24  # you may need to change ip addresses, e.g. 100.100.107.0/24 and so on
          gateway: 100.100.107.1