version: "3.9"

services:
  portfolio-service:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: bash /code/docker-entrypoint.sh
    container_name: portfolio-service
    image: portfolio-service
    volumes:
      - .:/code
      - ../portfolio-service-logs:/logs
      - static_volume:/code/static
      - media_volume:/code/portfolio/data/media
    expose:
      - 8000
    env_file: ./.env

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/code/static
      - media_volume:/code/portfolio/data/media
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      - portfolio-service

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  static_volume:
  media_volume:
