name: CI for branches

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "main"

env:
  POSTGRES_HOST_AUTH_METHOD: trust
  DATABASE_NAME: "portfolio-service"
  DATABASE_ENGINE: "db.sqlite3"
  SECRET_KEY: "6cge_dd_!6mx@u0olset6)gib-z*!vum048q4k#e-^(#+%#3$5"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        db: [sqlite]
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/development.txt

      - name: Lint with Flake8
        run: |
          flake8 .
          export

      - name: Run Tests
        run: |
          export DATABASE_NAME="portfolio-service"
          export DATABASE_ENGINE="db.sqlite3"
          pytest
